version: '3'

services:
  proxy:
    image: nginx:1.11 # this will use the latest version of 1.11.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    build: ./http
#   image: php:8.0-apache
    volumes:
      - ./http:/var/www/html/ 
  db: 
    image: mysql:latest
    ports: 
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: "cruddb"
      #MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      #MYSQL_ALLOW_EMPTY_PASSWORD: "rootpassword"
      #MYSQL_RANDOM_ROOT_PASSWORD: "rootpassword"


