version: '3'

services:
  proxy:
    image: nginx:1.11 # this will use the latest version of 1.11.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    build: ./http
#   image: php:8.0-apache
    volumes:
      - ./http:/var/www/html/ 
  db: 
    image: mysql:latest
    ports: 
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: "cruddb"
      #MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      #MYSQL_ALLOW_EMPTY_PASSWORD: "rootpassword"
      #MYSQL_RANDOM_ROOT_PASSWORD: "rootpassword"
  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    ports:
      - 9104:9104
    volumes:
      - ./mysql-exporter/.my.cnf:/root/.my.cnf
    environment:
      - DATA_SOURCE_NAME="exporter:exporterpassword@(127.0.0.1:3306)/"
      - collect.info_schema.processlist
      - collect.info_schema.innodb_metrics
      - collect.info_schema.tablestats
      - collect.info_schema.tables
      - collect.info_schema.userstats
      - collect.engine_innodb_status
    depends_on:
      - db
